#!/bin/sh

set -x

if [ -z "$1" ]; then
    echo "Error: no interface specified"
    exit 1
fi

ip tuntap add "$1" mode tap user "$(whoami)" 2>/dev/null || true
ip addr replace 192.168.1.1/24 dev "$1"
ip link set "$1" up

sysctl -w net.ipv4.ip_forward=1

exit 0